services:
  - type: web
    name: career-assignment-backend
    env: java
    rootDir: backend
    buildCommand: "./mvnw clean package"
    startCommand: "java -jar target/full-project-0.0.1-SNAPSHOT.jar"
    autoDeploy: true
    envVars:
      - key: JAVA_VERSION
        value: "17"
      - key: FRONTEND_ORIGINS
        value: "https://lokesh15kl.github.io"
      - key: SMTP_USERNAME
        sync: false
      - key: SMTP_PASSWORD
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: DATABASE_USERNAME
        sync: false
      - key: DATABASE_PASSWORD
        sync: false
      - key: HUGGINGFACE_API_KEY
        sync: false
